### ISSUE TITLE
issue with parsing config where curly brackets are used as regex repetitions

### ISSUE THREAD

**Issue by sgtmz** [ckishimo/juniper_display_set#2]
https://github.com/ckishimo/juniper_display_set/blob/2fe98a3b90afe70f0bf5dd6a1c122eb037d129b3/junos_converter.py#L33

on line 33 you are adding newlines after/before curly brackets. 
Unfortunately curly brackets can be used as repetition within regular expressions in junos. 
for example, this scripts breaks with a config like this:

`
groups {
    NAME {
        policy-options {
            as-path-group NAME2 {
                as-path NAME3 "^123 456{2,}$";
            }
        }
    }
}
`
that config is meant to match 2 or more repetitions of AS number 456, but unfortunately breaks the parsing of this script. 
I think this could be solved by looking at open/closed quotes before replacing curly brackets with newline+brackets, so this could ignore curly brackets that are within quotes.

**Comment by ckishimo** [comment]
@sgtmz indeed! thanks for reporting. I just pushed an update directly into master...

**Comment by sgtmz** [comment]
thanks for the quick fix!
